### ISSUE TITLE
Polyvore dataset link is incorrect

### ISSUE THREAD

**Issue by WangXin93** [mvasil/fashion-compatibility#1]
Hi，

I tried to run this project but found the link of the dataset is incorrect, which direct met to a 404 page.

Is that URL a typo error?

**Comment by gcucurull** [comment]
The other dataset that they use, the Maryland Polyvore dataset can be found here: https://github.com/xthan/polyvore-dataset

**Comment by melifluos** [comment]
Do you plan to fix the link to the dataset that is currently going to a 404 page? I would like to try to replicate your results. Thanks, Ben.

**Comment by mvasil** [comment]
Link to dataset is now updated!
