### ISSUE TITLE
How to generate hglmm pca fisher vector and typespaces.p file

### ISSUE THREAD

**Issue by Expert68** [mvasil/fashion-compatibility#15]
I want to generate hglmm pca fisher vector and typespaces.p file for a new dataset. Much thanks if you would provide the script for me.

**Comment by BryanPlummer** [comment]
The typespaces file is just an enumeration of all unique pairs of item types in the training set.  HGLMM features can be computed from code released by the authors who introduced those features.  Versions of this codebase are also in other paper's released code, e.g.,

https://github.com/BryanPlummer/pl-clc/tree/master/external/hglmm_fv

That said, you could get most of the performance by using another pre-trained embedding, even if the HGLMM features are typically a bit better.  An alternative I would recommend that is readily available is:

https://fasttext.cc/docs/en/english-vectors.html

In the next couple weeks or so you should be able to the individual tokens of precomputed HGLMM tokens through [my personal webpage](http://bryanplummer.com/) once they are are available, which you should be able to use on different datasets, but they are being released in conjunction with an ICCV19 paper on language features so we are still getting them together at this point.

**Comment by Expert68** [comment]
Thanks for your help, your code helped me a lot.
