### ISSUE TITLE
Coarse types

### ISSUE THREAD

**Issue by gcucurull** [mvasil/fashion-compatibility#2]
Hello,

I see from your dataloader that you use the attribute `coarse_type` for each product, which types have you used for the Maryland Polyvore dataset? In their case each item has very fine-grained category, have you mapped these categories to a coarser set of categories? Or do you work with the fine-grained categories? 

Thanks!

**Comment by BryanPlummer** [comment]
Using the fine-grained categories you wouldn't be able to get enough samples to learn a projection.  Instead, we used the index of the item, which roughly corresponded to a type.  While this doesn't provide the same strict typing scenario that the Polyvore Outfits dataset does, it provides further evidence (coupled with the random assignment experiments) that there is some redundancy there and a different embedding for each pairwise comparison isn't strictly necessary.

**Comment by tianyu-su** [comment]
> Using the fine-grained categories you wouldn't be able to get enough samples to learn a projection. Instead, we used the index of the item, which roughly corresponded to a type. While this doesn't provide the same strict typing scenario that the Polyvore Outfits dataset does, it provides further evidence (coupled with the random assignment experiments) that there is some redundancy there and a different embedding for each pairwise comparison isn't strictly necessary.

So, the results of Maryland Dataset in your paper, how do you map the fine-grained categories to semantic (coarse) type?
I find  the number of  id in   `categoires.csv` is smaller than Maryland dataset. Do you ignore some samples when you test on this dataset?

Thanks

**Comment by marzooq-unbxd** [comment]
I am trying to use the already trained model in order to run it on a bunch of random outfits outside polyvore
But i dont know how many typespaces to use , I only got
```
'tops', 'jewellery', 'bottoms', 'bags', 'shoes', 'hats', 'accessories', 'all-body', 'outerwear', 'sunglasses', 'scarves'
```
as categories in the polyvore dataset I used.
I am not able to map a new product to the typespaces , since I cant get the list of all typespaces.
Can anyone help me?
